### ISSUE TITLE
SCR and W3R

### ISSUE THREAD

**Issue by ZLOFENIX** [CrackSnoop/cracksnoop#1]
They not denuvo protected ist blizzard drm and online. Also scr cracked by me years ago.

**Comment by NayamAmarshe** [comment]
Just to confirm, by W3R you mean Warcraft III Reforged and by SCR you mean Starcraft Remastered right?

**Comment by ZLOFENIX** [comment]
Yes

**Comment by NayamAmarshe** [comment]
Updated the list.
In future, if you have any suggestions, please feel free to edit the list and add a pull request.

Closing the issue and marking as fixed :)
