### ISSUE TITLE
Sniper: Ghost Warrior Contracts 2

### ISSUE THREAD

**Issue by Unagi420** [CrackSnoop/cracksnoop#16]
Sniper: Ghost Warrior Contracts 2 get cracked : 
- Sniper_Ghost_Warrior_Contracts_2-FLT
- Sniper.Ghost.Warrior.Contracts.2.Deluxe.Arsenal.Edition.Steam.Rip-InsaneRamZes

**Comment by cracksnooper** [comment]
Updated, sorry for the delay.
